spring:
  application:
    name: sample
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(yc1AX+NofkeaFYWIUyzq/cPb0s4AVdshejqPV9p38VtCYaZK/DwriG0VcFrLaVpg)
    username: ENC(xcfOErAgL5MUnXVs07JyD3DJ65+/mIHC)
    password: ENC(xcfOErAgL5MUnXVs07JyD3DJ65+/mIHC)

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.khg.sample